server:
  port: 8181

bot:
  username: "${BOT_NAME:car_servcie_light_bot}"
  token: "${BOT_TOKEN:8143865220:AAFx1frgpPfAlqV4wdN6wXG9cIXmUEO3ruU}"

  button:
    names:
      details: Details
      max-year: Max year
      min-year: Min year
      body-style: Body style
      number-of-owners: Number of owners
      max-mileage: Max millage
      clean: Clean
      search-dashboard: Search dashboard
      delete: Delete
      apply-and-search: Apply and search
      close: Close
  commands:
      stop-name: stop
      stop-description: stop the search
